version: '3'
services:
  db:
    image: postgres
    container_name: rspec-practice-db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  web:
    build: .
    container_name: rspec-practice-web
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rspec-practice
    ports:
      - "3000:3000"
    depends_on:
      - db